### ISSUE TITLE
Keep up with changes/fixes of the Drupal version

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/i18n#24]
There have been several bugfixes and releases for i18n Drupal version since the Backdrop version got forked.

TODO: evaluate, which one's are usable and make sense for the Backdrop version (which is pretty much of a rewrite).

https://www.drupal.org/project/i18n/releases

**Comment by indigoxela** [comment]
A new version has been released, evaluate...

- [x] NA - not reproducible | [b064349](https://git.drupalcode.org/project/i18n/-/commit/b0643499185173c9bfc19213a3422e238c17e28c) | [Issue #2054587 by marabak: Error from i18n : Notice: Undefined index: form_id in i18n_field_field_widget_form_alter()](http://drupal.org/node/2054587)
- [x] N/A - it actually breaks parts of field translation | [3b532df](https://git.drupalcode.org/project/i18n/-/commit/3b532dfc447e077fe9d7895af09262f43e3190d6) | [Issue #1829050 by fengtan, ciss, Jelle_S: Translate field options with allowed_values_function](http://drupal.org/node/1829050)
- [x] N/A not reproducible | [da37cb9](https://git.drupalcode.org/project/i18n/-/commit/da37cb9af674cfbb2649ffcb8aaf21a1a325624b) | [Issue #1188334 by robertom, drclaw, sharky999: Translate interface for nodes, fields, etc. show wrong language in the column](http://drupal.org/node/1188334)
- [x] N/A | [a6cbf3f](https://git.drupalcode.org/project/i18n/-/commit/a6cbf3f0453fbcce9533b899ef0fe823edd79bbe) | [Issue #3156025 by monph: Fix typo on README](http://drupal.org/node/3156025)
- [x] N/A that module got removed | [85696e2](https://git.drupalcode.org/project/i18n/-/commit/85696e266393c90a211cab9cff012450b1174972) | [Issue #3120520 by geoffray: Fix code comment](http://drupal.org/node/3120520)
- [x] N/A has already been fixed - differently | [7764548](https://git.drupalcode.org/project/i18n/-/commit/7764548adf5e82d628f159bb2bb93f062bbb6883) | [Issue #3003386 by michel.g, joshf, d.laadidi: The Global Language's value changes if the translation is activated for the taxonomy](http://drupal.org/node/3003386)
- [x] N/A we use a different hook with totally different code | [a6a6384](https://git.drupalcode.org/project/i18n/-/commit/a6a63849ec2419123538269e3c869b333c78840b) | [Issue #3004899 by Pranali.addweb, reggaefish: Notice: Undefined index: language in i18n_node_node_view()](http://drupal.org/node/3004899)
- [x] N/A partly not applicable, partly fixed differently | [aed7638](https://git.drupalcode.org/project/i18n/-/commit/aed7638933060d0a70675eb2624020998e5acd7d) | [Issue #3208028 by Taran2L, DamienMcKenna, joseph.olstad, stefanos.petrakis: PHP 8.0 compatibility for i18n](http://drupal.org/node/3208028)

Conclusion: not a single change has been made.
3b532df turned out to actually break other field translation stuff and isn't reproducible anyway.

**Comment by indigoxela** [comment]
Version 7.x-1.32 has been released for Drupal, it contains one fix:

[Field labels&descriptions are lost on string refresh](https://www.drupal.org/project/i18n/issues/2286651)

They're not actually lost, as it's a caching problem. https://git.drupalcode.org/project/i18n/-/commit/b8e8f3a

**Comment by indigoxela** [comment]
Version [7.x-1.34](https://www.drupal.org/project/i18n/releases/7.x-1.34) has been released.

Several php 8 compat issues, which should actually already be fixed in B version, but have a closer look.
